# GitHub action to build software.
# Linux builds include pre-built dependencies via containers.
# The Windows and MacOS builds build dependencies each run.

name: Build
on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  ubuntu_20_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-20.04:latest

    steps:
      - name: Checkout xreg repository master branch
        uses: actions/checkout@v2
        with:
          repository: rg2/xreg
          path: ./xreg-git
      - name: Checkout this repo (Regi2D3D-IPCAI2020)
        uses: actions/checkout@v2
        with:
          path: ./regi2d3d-ipcai2020
      - name: Build xreg master branch
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_xreg_cmake_build
        shell: bash
      - name: Build this repo (Regi2D3D-IPCAI2020)
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_regi2d3d_ipcai2020_cmake_build
        shell: bash
      - name: Install packages needed to create distribution file
        run: ./xreg-git/dist/ubuntu_dist_pkgs
        shell: bash
      - name: Create distribution file
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_make_dist ubuntu-20.04
        shell: bash
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-20.04-build
          path: regi2d3d-ipcai2020-ubuntu-20.04.tar.gz

  ubuntu_18_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-18.04:latest

    steps:
      - name: Checkout xreg repository master branch
        uses: actions/checkout@v2
        with:
          repository: rg2/xreg
          path: ./xreg-git
      - name: Checkout this repo (Regi2D3D-IPCAI2020)
        uses: actions/checkout@v2
        with:
          path: ./regi2d3d-ipcai2020
      - name: Build xreg master branch
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_xreg_cmake_build
        shell: bash
      - name: Build this repo (Regi2D3D-IPCAI2020)
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_regi2d3d_ipcai2020_cmake_build
        shell: bash
      - name: Install packages needed to create distribution file
        run: ./xreg-git/dist/ubuntu_dist_pkgs
        shell: bash
      - name: Create distribution file
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_make_dist ubuntu-18.04
        shell: bash
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-18.04-build
          path: regi2d3d-ipcai2020-ubuntu-18.04.tar.gz

  ubuntu_16_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-16.04:latest

    steps:
      - name: Checkout xreg repository master branch
        uses: actions/checkout@v2
        with:
          repository: rg2/xreg
          path: ./xreg-git
      - name: Checkout this repo (Regi2D3D-IPCAI2020)
        uses: actions/checkout@v2
        with:
          path: ./regi2d3d-ipcai2020
      - name: Build xreg master branch
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_xreg_cmake_build
        shell: bash
      - name: Build this repo (Regi2D3D-IPCAI2020)
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_regi2d3d_ipcai2020_cmake_build
        shell: bash
      - name: Install packages needed to create distribution file
        run: ./xreg-git/dist/ubuntu_dist_pkgs
        shell: bash
      - name: Create distribution file
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_make_dist ubuntu-16.04
        shell: bash
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-16.04-build
          path: regi2d3d-ipcai2020-ubuntu-16.04.tar.gz

  centos_7_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-centos-7:latest

    steps:
      - name: Checkout xreg repository master branch
        uses: actions/checkout@v2
        with:
          repository: rg2/xreg
          path: ./xreg-git
      - name: Checkout this repo (Regi2D3D-IPCAI2020)
        uses: actions/checkout@v2
        with:
          path: ./regi2d3d-ipcai2020
      - name: Build xreg master branch
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_xreg_cmake_build
        shell: bash
      - name: Build this repo (Regi2D3D-IPCAI2020)
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_regi2d3d_ipcai2020_cmake_build
        shell: bash
      - name: Install packages needed to create distribution file
        run: ./xreg-git/dist/centos_dist_pkgs
        shell: bash
      - name: Create distribution file
        run: ./regi2d3d-ipcai2020/.github/workflows/linux_make_dist centos-7
        shell: bash
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v2
        with:
          name: centos-7-build
          path: regi2d3d-ipcai2020-centos-7.tar.gz

  windows_build:
    runs-on: windows-2019

    steps:
      - name: Checkout xreg repository master branch
        uses: actions/checkout@v2
        with:
          repository: rg2/xreg
          path: xreg-git
      - name: Checkout this repo (Regi2D3D-IPCAI2020)
        uses: actions/checkout@v2
        with:
          path: regi2d3d-ipcai2020
      - name: Setup Visual C++ environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build xreg master branch
        run: regi2d3d-ipcai2020\.github\workflows\win_xreg_build.cmd
        shell: cmd
      #- name: Build this repo (Regi2D3D-IPCAI2020)
      #  run: regi2d3d-ipcai2020\.github\workflows\win_regi2d3d_ipcai2020_build.cmd
      #  shell: cmd
      #- run: .github\workflows\win_make_dist.cmd
      #  shell: cmd
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: win-64-build
      #    path: xreg-win64.zip
